"""FastAPI endpoints for initiating and tracking DigiLocker identity verifications."""

from fastapi import APIRouter, Depends, Request, status

from app.api.deps import get_current_user_id, get_verification_service
from app.schemas.verification import VerificationInitiateRequest, VerificationInitiateResponse
from app.services.verification import VerificationService

__all__ = ["router"]

router = APIRouter()


@router.post(
    "/initiate",
    response_model=VerificationInitiateResponse,
    status_code=status.HTTP_201_CREATED,
    summary="Initiate a new DigiLocker identity verification",
    description=(
        "Start a new verification flow by logging the request, setting up "
        "a Redis session state, acquiring flow locks, and returning the "
        "redirection authorization URL to redirect the user to DigiLocker."
    ),
)
async def initiate_verification(
    body: VerificationInitiateRequest,
    request: Request,
    user_id: str = Depends(get_current_user_id),
    verification_service: VerificationService = Depends(get_verification_service),
) -> VerificationInitiateResponse:
    """FastAPI endpoint to start a DigiLocker verification session."""
    # Extract request IP address for rate limiting
    ip_address = request.headers.get("x-forwarded-for")
    if ip_address:
        ip_address = ip_address.split(",")[0].strip()
    else:
        ip_address = request.client.host if request.client else None

    # Retrieve the correlation ID generated by RequestIDMiddleware
    correlation_id = getattr(request.state, "correlation_id", "unknown-correlation-id")

    # Delegate flow orchestrations to the VerificationService
    verification_id, authorization_url = await verification_service.initiate_verification(
        user_id=user_id,
        client_redirect_uri=body.redirect_uri,
        ip_address=ip_address,
        correlation_id=correlation_id,
    )

    return VerificationInitiateResponse(
        verification_id=verification_id,
        authorization_url=authorization_url,
    )
